Write-Output "___________"
Write-Output "< thank you >"
Write-Output " -----------"
Write-Output "        \   ^__^"
Write-Output "         \  (oo)\_______"
Write-Output "            (__)\       )\/\"
Write-Output "                ||----w |"
Write-Output "                ||     ||"
